platform :ios, '16.0'

inhibit_all_warnings!

target 'Eventorias' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'EventoriasTests' do
  inherit! :search_paths
  end

  target 'EventoriasUITests' do
  inherit! :search_paths
  end
end
